\input texinfo
@setfilename internet.info

@titlepage
@title Internet
@end titlepage

@contents

@ifnottex
@node Top
@top Internet

This manual is for Internet 0.1.0
@end ifnottex

@menu
* Overview::
* Dependencies::
* Configuration::
* Usage::
* License::
* Index::
@end menu

@node Overview
@chapter Overview

@cindex Overview

Internet is an Emacs package that provides a variety of ways to
connect to the internet.

Before using setup the dependencies and configuration for your desired
connection methods.

Functionality:

@itemize @bullet

@item
Methods of connecting to the internet

@itemize @minus

@item
Ethernet

@item
Wireless

@item
Ethernet and openvpn

@item
Wireless and openvpn

@end itemize

@item
Disconnect for the above connecting options

@item
Add and remove wireless network configurations

@end itemize

@node Dependencies
@chapter Dependencies

@cindex Dependencies

@section Ethernet Connection

@cindex Ethernet Connection

If you are connecting using Ethernet you need to have these programs
installed:

@itemize @bullet

@item
@command{ip-link}

@item
@command{dhclient}

@item
@command{sudo}

@end itemize

@section Ethernet OpneVPN Connection

@cindex Ethernet OpenVPN Connection

If you are connecting using Ethernet and OpenVPN you need to have
these programs installed:

@itemize @bullet

@item
@command{ip-link}

@item
@command{dhclient}

@item
@command{openvpn}

@item
@command{sudo}

@end itemize

@section Wireless Connection

@cindex Wireless Connection

If you are connecting using wireless you need to have these programs
installed:

@itemize @bullet

@item
@command{rfkill}

@item
@command{ip-link}

@item
@command{wpa_supplicant}

@item
@command{dhclient}

@item
@command{sudo}

@end itemize

@section Wireless Openvpn Connection

@cindex Wireless OpenVPN Connection

If you are connecting using wireless and OpenVPN you need to have
these programs installed:

@itemize @bullet

@item
@command{rfkill}

@item
@command{ip-link}

@item
@command{wpa_supplicant}

@item
@command{dhclient}

@item
@command{openvpn}

@item
@command{sudo}

@end itemize

@section Creating Wireless Configurations

@cindex Creating Wireless Configurations

If you are going to use this package to create wireless configurations
then you need to have these programs installed:

@itemize @bullet

@item
@command{wpa_passphrase}

@item
@command{sudo}

@end itemize
